config/routes.rb
Rails.application.routes.draw do
  
  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :users, controllers: { sessions: "users/sessions", registrations: "users/registrations" }

  get 'chapter/new'
  get 'chapter/show'
  
  post "markdown/preview"
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  #books
  get 'books/new'
  get 'books/create'
  get 'books/show'

  scope '(:locale)' do
    resources :users
    resources :books do
      resources :chapter
    resources :comments
    end
    match '/profile', to: 'users#profile', via: 'get'
    match '/help', to: 'static_pages#help', via: 'get'
    match '/about', to: 'static_pages#about', via: 'get'  
    match '/contact', to: 'static_pages#contact', via: 'get'
    match 'profile/addbook', to: 'books#new', via: 'get'
    match 'profile/mystories', to: 'users#show_stories', via: 'get'
  end
  root 'static_pages#home'

#  get 'users/show'

  

  
  #get 'users/new'

  
  devise_scope :user do
    get "/login" => "users/sessions#new"
    post "/login" => "users/sessions#create"
    get "/logout" => "users/sessions#destroy"
    get "profile/edit" => "users/registrations#edit"
  end

  

  
  match '/signup',  to: 'users#new', via: 'get'
  


  get '*unmatched_route', :to => 'application#not_found'
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  mount_uploader :avatar, AvatarUploader
  has_many :books, dependent: :destroy
  has_many :comments, dependent: :destroy
  ratyrate_rater
  acts_as_voter
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_filter :configure_sign_up_params
  before_filter :configure_account_update_params
 

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    super

  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  
  def configure_sign_up_params
    #devise_parameter_sanitizer.for(:sign_up) << :attribute
    #params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]
  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :user_signed_in?, only: [:show]
  
  def profile
    if not user_signed_in?
      redirect_to login_path
      return
    end
    @books = current_user.books.paginate(page: params[:page], :per_page => 10)
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books.paginate(page: params[:page], :per_page => 10)
  end

  def edit
    redirect_to edit_user_registration_path
  end

  def index
    @users = User.paginate(page: params[:page], :per_page => 5)
  end

  def show_stories
    @books = current_user.books.paginate(page: params[:page], :per_page => 10)
      
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirm Password" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>

  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>
<%= will_paginate @users %>

<ul class="users">
  <% @users.each do |user| %>
    <li>
      <% if user.avatar.blank? %>
		<%= link_to image_tag("default.jpg", alt: "AVA"), '#' %>
		<% else %>
		
		<%= image_tag(user.avatar) %>
		<% end %>
      <%= link_to user.name, user %>
    </li>
  <% end %>
</ul>

<%= will_paginate @users %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/profile.html.erb
<% provide(:title, current_user.name) %>
<ul>
	<li><%= link_to t('myprofile'),   profile_path %></li>
	<li><%= link_to t('myreaders'),   '#' %></li>
	<li><%= link_to t('stories'),   profile_mystories_path %></li>
	<li><%= link_to t('settings'),   profile_edit_path %></li>
	<li><%= link_to t('achieves'),   '#' %></li>
	<% if current_user.role == 2 %>
	<li><%= link_to t('admin_panel'),   rails_admin_path %></li>
	<% end %>
</ul>

<div class="row">
	<aside class="span4">
	<section>
		<h1>
		<% if current_user.avatar.blank? %>
		<%= link_to image_tag("default.jpg", alt: "AVA"), '#' %>
		<% else %>
		
		<%= image_tag(current_user.avatar) %>
		<% end %>
			<%= current_user.name %>
		</h1>
	</section>
	</aside>
	<a class="btn btn-default" href="profile/addbook" type="submit">
      		<%= t('add_story') %>
        </a>
	<div class="span8">
		
	  <% if @current_user.books.any? %>
      	<h3>Stories (<%= @current_user.books.count %>)</h3>
      	<%= will_paginate @books %>
      		<ul class="books">
			  <% @books.each do |book| %>
			    <li>
			      <%= link_to book.name, book %>
				  <span class="timestamp">
				    Posted <%= time_ago_in_words(book.created_at) %> ago.
				  </span>
				  <%= rating_for book, "rate" , :disable_after_rate => true, :imdb_avg => true %>
			    </li>
			  <% end %>
			</ul>
      	<%= will_paginate @books %>
    <% end %>		
	</div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
	<aside class="span4">
	<section>
		<h1>
		<% if @user.avatar.blank? %>
		<%= link_to image_tag("default.jpg", alt: "AVA"), '#' %>
		<% else %>
		
		<%= image_tag(@user.avatar) %>
		<% end %>
			<%= @user.name %>
		
		</h1>
	</section>
	</aside>

	<div class="span8">
		
	  <% if @user.books.any? %>
      	<h3>Stories (<%= @user.books.count %>)</h3>
      	<%= will_paginate @books %>
      		<ul class="books">
			  <% @books.each do |book| %>
			    <li>
			      <%= link_to book.name, book %>
				  <span class="timestamp">
				    Posted <%= time_ago_in_words(book.created_at) %> ago.
				  </span>
			    </li>
			  <% end %>
			</ul>
      	<%= will_paginate @books %>
    <% end %>

		
	</div>
</div>

app/views/users/show_stories.html.erb
<% provide(:title, 'My Stories') %>
<h1>My Stories</h1>
<a class="btn btn-default" href="addbook" type="submit">
      		Add Story
 </a>
<%= will_paginate @books %>

<ul class="books">
  <% @books.each do |book| %>
    <li>
        <%= link_to book.name, book %>
        <span class="timestamp">
				    Posted <%= time_ago_in_words(book.updated_at) %> ago.
				  </span>
    </li>
  <% end %>
</ul>

<%= will_paginate @books %>