config/routes.rb
Rails.application.routes.draw do
  
  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :users, controllers: { sessions: "users/sessions", registrations: "users/registrations" }

  get 'chapter/new'
  get 'chapter/show'
  
  post "markdown/preview"
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  #books
  get 'books/new'
  get 'books/create'
  get 'books/show'

  scope '(:locale)' do
    resources :users
    resources :books do
      resources :chapter
    resources :comments
    end
    match '/profile', to: 'users#profile', via: 'get'
    match '/help', to: 'static_pages#help', via: 'get'
    match '/about', to: 'static_pages#about', via: 'get'  
    match '/contact', to: 'static_pages#contact', via: 'get'
    match 'profile/addbook', to: 'books#new', via: 'get'
    match 'profile/mystories', to: 'users#show_stories', via: 'get'
  end
  root 'static_pages#home'

#  get 'users/show'

  

  
  #get 'users/new'

  
  devise_scope :user do
    get "/login" => "users/sessions#new"
    post "/login" => "users/sessions#create"
    get "/logout" => "users/sessions#destroy"
    get "profile/edit" => "users/registrations#edit"
  end

  

  
  match '/signup',  to: 'users#new', via: 'get'
  


  get '*unmatched_route', :to => 'application#not_found'
end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/book.rb
class Book < ActiveRecord::Base
	belongs_to :user
	validates :user_id, presence: true
	validates :name, presence: true, length: {maximum: 50}

	default_scope -> { order('updated_at DESC') }
	
	has_many :chapters, dependent: :destroy
	has_many :comments, dependent: :destroy

	ratyrate_rateable "rate"



	def self.search(search)
	  if search
	    Book.where('name LIKE ?', "%#{search}%")
	  else
	    Book.all
	  end
	end


end

app/models/chapter.rb
class Chapter < ActiveRecord::Base
	belongs_to :book
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :book
	belongs_to :user
	acts_as_votable
end

app/models/like.rb
class Like < ActiveRecord::Base
	
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating.rb
class Rating < ActiveRecord::Base
end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/tag.rb
class Tag < ActiveRecord::Base
	
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  mount_uploader :avatar, AvatarUploader
  has_many :books, dependent: :destroy
  has_many :comments, dependent: :destroy
  ratyrate_rater
  acts_as_voter
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :user_signed_in?, only: [:show]

  def new
    if user_signed_in?
      @book = Book.new
    else
      redirect_to login_path
    end
  end

  def create
    @book = Book.new(book_params)    # Not the final implementation!
    @book.user_id = current_user.id
    if @book.save!
      redirect_to @book
    else
      render 'new'
    end
  end

  def show
  	@book = Book.find(params[:id])
    @chapters = @book.chapters.paginate(page: params[:page], :per_page => 10)
    @comments = @book.comments.paginate(page: params[:page], :per_page => 50)
    @comment = Comment.new
  end

  def index
  	@books = Book.search(params[:search]).paginate(page: params[:page], :per_page => 3)
    @book_s = Book.search(params[:search])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    

  end

  private

  def book_params
    params.require(:book).permit(:name, :genre)
  end
end

app/controllers/chapter_controller.rb
class ChapterController < ApplicationController
  def new
  	@book_chapter = Chapter.new
    @book_chapter.book_id = params[:book_id]
  end

  def create
  	@chapter = Chapter.new(chapter_params)
    @chapter.book_id = params[:book_id]
    if @chapter.save!
      redirect_to books_path.to_s + "/" + @chapter.book_id.to_s
    else
      render 'new'
    end
  end

  def show
  	@chapter = Chapter.find(params[:id])
  end

  def edit
  	@chapter = Chapter.find(params[:id])
  end

  def update
    @chapter = Chapter.find(params[:id])
    @chapter.update!(chapter_params)
    if @chapter.save!
      redirect_to book_chapter_path
    else
      render 'edit'
    end
  end

  private

  def chapter_params
    params.require(:chapter).permit(:name, :content)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def index
	  @comment = Comment.new(comment_params)
	  @comment.book_id = params[:book_id]
	  @comment.user_id = current_user.id
	  @comment.save!
	  redirect_to book_path(@comment.book_id)
	end

	private

  	def comment_params
      params.require(:comment).permit(:content)
	end
end

app/controllers/rater_controller.rb
class RaterController < ApplicationController

  def create
    if user_signed_in?
      obj = params[:klass].classify.constantize.find(params[:id])
      obj.rate params[:score].to_f, current_user, params[:dimension]
      render :json => true
    else
      render :json => false
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :user_signed_in?, only: [:show]
  
  def profile
    if not user_signed_in?
      redirect_to login_path
      return
    end
    @books = current_user.books.paginate(page: params[:page], :per_page => 10)
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books.paginate(page: params[:page], :per_page => 10)
  end

  def edit
    redirect_to edit_user_registration_path
  end

  def index
    @users = User.paginate(page: params[:page], :per_page => 5)
  end

  def show_stories
    @books = current_user.books.paginate(page: params[:page], :per_page => 10)
      
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
	def full_title(page_title)
		base_title = "Stories"
		if page_title.empty?
			base_title
		else
			"#{base_title} | #{page_title}"
		end
	end

	def greeting()
		((user_signed_in?) ? current_user.name : "Guest")
	end

	def markdown(text)
    renderer = Redcarpet::Render::HTML.new(hard_wrap: true, filter_html: true)
    options = {
        autolink: true,
        no_intra_emphasis: true,
        fenced_code_blocks: true,
        lax_html_blocks: true,
        strikethrough: true,
        superscript: true,
        space_after_headers: true
    }
    Redcarpet::Markdown.new(renderer, options).render(text).html_safe
  	end


  	def latest_stories

  	end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/chapter_helper.rb
module ChapterHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/markdown_helper.rb
module MarkdownHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_book.html.erb
<li>
  <span class="bookname"><%= book.name %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(book.created_at) %> ago.
  </span>
</li>

app/views/books/create.html.erb
<h1>Books#create</h1>
<p>Find me in app/views/books/create.html.erb</p>

app/views/books/edit.html.erb
<% provide(:title, 'Edit Story') %>
<h1>Edit Story</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@book) do |f| %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :genre %>
      <%= f.text_field :genre %>

      <%= f.submit "Update!", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div> 

app/views/books/index.html.erb
<% provide(:title, 'All Stories') %>
<h1>All Stories</h1>
<%= will_paginate @books %>

<ul class="books">
  <% @books.each do |book| %>
    <li>
        <%= link_to book.name, book %>
    </li>
  <% end %>
</ul>

<%= will_paginate @books %>

app/views/books/new.html.erb
<% provide(:title, 'New Story') %>
<h1>New Story</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@book) do |f| %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :genre %>
      <%= f.text_field :genre %>

      <%= f.submit "Create!", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div> 

app/views/books/show.html.erb
<% provide(:title, @book.name) %>

<div class="row">
	<%= rating_for @book, "rate" , :disable_after_rate => true, :imdb_avg => true %>
	<div class="span8">
		<% if user_signed_in? %>
			<% if current_user.id == @book.user_id %>
			<a class="btn btn-default" href= <%= @book.id.to_s + "/chapter/new"%>  type="submit">
      			Add New Chapter
   		 	</a>
   		 	<% else %>
   		 	<%= "Author is " + @book.user.name %>
   		 	<% end %>
   		<% end %>  
	  <% if @book.chapters.any? %>
      	<h3> <%= @book.name %> </h3>
      	<%= will_paginate @chapters %>
      		<ul class="books">
			  <% @chapters.each do |chapter| %>
			    <li>
			      <%= link_to chapter.name, book_chapter_path(@book.id, chapter.id) %>
				  <span class="timestamp">
				  
				  </span>
			    </li>
			  <% end %>
			</ul>
      	<%= will_paginate @chapters %>
      <% end %>		
	
	<p>Comments : </p></br>
	<%= will_paginate @comments %>
		<ul class="comment">
	  <% @comments.each do |comment| %>
	    <li>
	      <%= markdown(comment.user.name + " : " + comment.content) %>
	    </li>
	  <% end %>
	</ul>
  	<%= will_paginate @comments %>
  	<% if user_signed_in? %>
  	<div class="row">
  		<div class="span6 offset3">
		<%= form_for @comment, url: book_comments_path(@book.id), html: {method: :get} do |f| %>

	      <%= f.label current_user.name + " : " %>
	      <%= f.text_field :content %>

	      <%= f.submit "leave comment", class: "btn btn-large btn-primary" %>
	    <% end %>
		</div>
	</div> 
	<% end %>
	</div>
</div>

app/views/chapter/edit.html.erb
<% provide(:title, 'Edit Chapter ' + @chapter.name) %>

<div class="row">
  <div class="span6 offset3">
    <%= bootstrap_form_for @chapter, url: book_chapter_path, html: {method: :patch} do |f| %>

      <%= f.text_field :name %>
      <%= f.text_area :content %>
      
      <%= f.submit "Update!", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div> 

app/views/chapter/new.html.erb
<% provide(:title, 'New Chapter') %>
<h1>New Chapter</h1>

<div class="row">
  <div class="span6 offset3">
    

	<%= bootstrap_form_for @book_chapter, url: book_chapter_index_path, html: {method: :post} do |f| %>

  
      <%= f.text_field :name %>
      <%= f.text_area :content %>

      <%= f.submit 'Create', class: "btn btn-large btn-primary" %>
    <% end %>    
  </div>
</div> 

app/views/chapter/show.html.erb
<h1><%= @chapter.name %> </h1>
<% if user_signed_in? %>
	<% if current_user.id == @chapter.book.user_id %>
	<a class="btn btn-default" href= <%= @chapter.id.to_s + "/edit" %> type="submit">
      		Edit Chapter
    </a>
    <% end %>
<% end %>


<%= markdown(@chapter.content) %>