config/routes.rb
Rails.application.routes.draw do
  
  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :users, controllers: { sessions: "users/sessions", registrations: "users/registrations" }

  get 'chapter/new'
  get 'chapter/show'
  
  post "markdown/preview"
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  #books
  get 'books/new'
  get 'books/create'
  get 'books/show'

  scope '(:locale)' do
    resources :users
    resources :books do
      resources :chapter
    resources :comments
    end
    match '/profile', to: 'users#profile', via: 'get'
    match '/help', to: 'static_pages#help', via: 'get'
    match '/about', to: 'static_pages#about', via: 'get'  
    match '/contact', to: 'static_pages#contact', via: 'get'
    match 'profile/addbook', to: 'books#new', via: 'get'
    match 'profile/mystories', to: 'users#show_stories', via: 'get'
  end
  root 'static_pages#home'

#  get 'users/show'

  

  
  #get 'users/new'

  
  devise_scope :user do
    get "/login" => "users/sessions#new"
    post "/login" => "users/sessions#create"
    get "/logout" => "users/sessions#destroy"
    get "profile/edit" => "users/registrations#edit"
  end

  

  
  match '/signup',  to: 'users#new', via: 'get'
  


  get '*unmatched_route', :to => 'application#not_found'
end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/book.rb
class Book < ActiveRecord::Base
	belongs_to :user
	validates :user_id, presence: true
	validates :name, presence: true, length: {maximum: 50}

	default_scope -> { order('updated_at DESC') }
	
	has_many :chapters, dependent: :destroy
	has_many :comments, dependent: :destroy

	ratyrate_rateable "rate"



	def self.search(search)
	  if search
	    Book.where('name LIKE ?', "%#{search}%")
	  else
	    Book.all
	  end
	end


end

app/models/chapter.rb
class Chapter < ActiveRecord::Base
	belongs_to :book
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :book
	belongs_to :user
	acts_as_votable
end

app/models/like.rb
class Like < ActiveRecord::Base
	
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating.rb
class Rating < ActiveRecord::Base
end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/tag.rb
class Tag < ActiveRecord::Base
	
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  mount_uploader :avatar, AvatarUploader
  has_many :books, dependent: :destroy
  has_many :comments, dependent: :destroy
  ratyrate_rater
  acts_as_voter
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :user_signed_in?, only: [:show]

  def new
    if user_signed_in?
      @book = Book.new
    else
      redirect_to login_path
    end
  end

  def create
    @book = Book.new(book_params)    # Not the final implementation!
    @book.user_id = current_user.id
    if @book.save!
      redirect_to @book
    else
      render 'new'
    end
  end

  def show
  	@book = Book.find(params[:id])
    @chapters = @book.chapters.paginate(page: params[:page], :per_page => 10)
    @comments = @book.comments.paginate(page: params[:page], :per_page => 50)
    @comment = Comment.new
  end

  def index
  	@books = Book.search(params[:search]).paginate(page: params[:page], :per_page => 3)
    @book_s = Book.search(params[:search])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    

  end

  private

  def book_params
    params.require(:book).permit(:name, :genre)
  end
end

app/controllers/rater_controller.rb
class RaterController < ApplicationController

  def create
    if user_signed_in?
      obj = params[:klass].classify.constantize.find(params[:id])
      obj.rate params[:score].to_f, current_user, params[:dimension]
      render :json => true
    else
      render :json => false
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def full_title(page_title)
		base_title = "Stories"
		if page_title.empty?
			base_title
		else
			"#{base_title} | #{page_title}"
		end
	end

	def greeting()
		((user_signed_in?) ? current_user.name : "Guest")
	end

	def markdown(text)
    renderer = Redcarpet::Render::HTML.new(hard_wrap: true, filter_html: true)
    options = {
        autolink: true,
        no_intra_emphasis: true,
        fenced_code_blocks: true,
        lax_html_blocks: true,
        strikethrough: true,
        superscript: true,
        space_after_headers: true
    }
    Redcarpet::Markdown.new(renderer, options).render(text).html_safe
  	end


  	def latest_stories

  	end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/chapter_helper.rb
module ChapterHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/markdown_helper.rb
module MarkdownHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav class="navbar-fixed-bottom">
  <small>
    Bookshelf by Vitaly Butoma
  </small>
  <nav>
    <ul>
      <li><%= link_to t('about'),   about_path %></li>
      <li><%= link_to t('contact'), contact_path %></li>
    </ul>
  </nav>
  </nav>
</footer>

app/views/layouts/_header.html.erb
 <nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <% if user_signed_in? %>
      <a class="navbar-brand" href="#"><%= greeting() %></a>
      <% else %>
      <a class="navbar-brand" href="#">Stories</a>
      <% end %>
    </div>

      
    <ul class="nav navbar-nav">

      <li class='search'>
      <%= form_tag books_path, :method => 'get' do %>
        
          <%= text_field_tag :search, params[:search] %>
          <%= submit_tag "Search", :name => nil %>
        
      <% end %>
      </li>
      <li><%= link_to t('home'),   root_path %></li>
       <li><%= link_to t('users'),   users_path %></li>
       <li><%= link_to t('books'),   books_path %></li>
       <li><%= link_to t('news'),   '#' %></li>
       <li><%= link_to t('help'),   help_path %></li>
       
       <% if user_signed_in? %>
       <li><%= link_to t('logout'),   logout_path %></li>
       <% else %>
       <li><%= link_to t('login'),   login_path %></li>
       <% end %>
       <li>

       <div id='banner'>
          <%= form_tag '#', class: 'locale', method: 'post' do %>
            <%= select_tag 'set_locale', options_for_select(LANGUAGES, I18n.locale.to_s), onchange: 'this.form.submit()' %>
            <!--<%= submit_tag 'submit' %>!-->
            <%= javascript_tag "$('.locale input').hide()" %>
          <% end %>
          <%= @page_title || t('title') %>
      </div>
      </li>

    </ul>
  </div>

</nav>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>